--Tables for application

-- CONFIGURATION
CREATE TABLE CONFIGURATION
(
 CONFIG_ID NUMERIC(20) NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 PROFILE VARCHAR(255),
 CONFIG_VALUE VARCHAR(255),
 VALUE_TYPE VARCHAR(10),
 PRIMARY KEY (CONFIG_ID)
);

CREATE UNIQUE INDEX UDX_CONFIGURATION_NAME on CONFIGURATION (NAME, PROFILE);

CREATE SEQUENCE SEQ_CONFIGURATION_ID START WITH 100;

-- Application configuration
INSERT INTO CONFIGURATION (CONFIG_ID, NAME, PROFILE, CONFIG_VALUE, VALUE_TYPE) values(101, 'capture.date.minimum', 'dev', '20120101000000', 'DATE');
INSERT INTO CONFIGURATION (CONFIG_ID, NAME, PROFILE, CONFIG_VALUE, VALUE_TYPE) values(102, 'account.expiration.in.days', 'dev', '90', 'INT');

-- Commit
commit;